;;; place-in-file.el --- saves your place in file -*- lexical-binding: t; -*-

;; Copyright (C) 2026 nukenukey

;; Version: 0.1
;; Created: Aug 16 2026
;; Keywords: files

;;; Commentary:
;; This package hooks into `file-file-hook' and `auto-save-hook'

;;; Code:

(defgroup place-in-file nil
	"Maintain points in opened files"
	:version "0.1"
	:group 'files)

(defcustom place-in-files-file (concat user-emacs-directory "place-in-files.el")
	"The file in which the places of files will be saved to"
	:type '(string)
	:group 'place-in-file)

;;;###autoload
(defun place-in-file/save-place ()
	(append places-in-files-list `((,(f-this-file) . ,(point)))))

;;;###autoload
(defun place-in-file/save-places ()
	(place-in-file/save-place)
	(with-temp-file place-in-files-file
		(insert (concat ";;; Automatically generated by `place-in-file' on " (time-stamp-string "%a %b %d %H:%M:%S %Y")))
		(insert "(setq places-in-files-list")
		(insert (concat "'" (prin1-to-string places-in-files-list))
		(insert ")"))))

;;;###autoload 
(defun place-in-file/load-places ()
	(if (f-exists-p (concat user-emacs-directory "place-in-files.el"))
			(load-file (concat user-emacs-directory "place-in-files.el"))
		(error "couldn't access place-in-file.el")))

;;;###autoload
(defun place-in-file/go-to-saved-place ()
	(when (assq (f-this-file) places-in-files-list)
		(goto-char (cdr (assq (f-this-file) places-in-files-list)))))

(add-hook 'auto-save-hook 'place-in-file/save-places)
(add-hook 'find-file-hook 'place-in-file/go-to-saved-place)

;;; place-in-file.el ends here
